# Nash Equilibria
## Snigdhayan Mahanta

Consider a `non-cooperative game` involving two or more players, where each player has a set of strategies. It is assumed that each player knows beforehand the strategies of the other players and the associated payoffs for each strategy (including one's own). A `Nash equilibrium` constitutes a set of strategy choices for each player, so that no player can increase the expected payoff by changing one's strategy as long as the other players stick to their choices. Under some reasonable hypotheses a `Nash equilibrium` always exists but it may not be unique.

I have used the python library `Nashpy` (https://nashpy.readthedocs.io/en/stable/index.html) to create a two player game (row player and column player) with $4$ strategic options for each player. Then I computed the `Nash equilibria` using the `Lemke-Howson algorithm`.

In [1]:
import nashpy as nash
import numpy as np

In [2]:
# Global parameters
n_rows = 4
n_cols = 4
choices = range(-9, 10)
size = n_rows*n_cols

In [3]:
# Create payoff matrices
np.random.seed(seed=42)
x = np.random.choice(choices, size = size, replace = True)
A = x.reshape(n_rows, n_cols)

y = np.random.choice(choices, size = size, replace = True)
B = y.reshape(n_rows, n_cols)

In [4]:
# Row player's payoff matrix
A

array([[-3,  5,  1, -2],
       [-3,  9,  1,  1],
       [-6, -2, -7, -8],
       [ 2, -4, -8, -9]])

In [5]:
# Column player's payoff matrix
B

array([[ 2,  2,  7,  0],
       [ 6,  5,  5,  9],
       [ 2, -7, -5,  9],
       [-3, -1, -3,  8]])

In [6]:
# Create a game and compute Nash equilibria
myGame = nash.Game(A, B)
myGame.lemke_howson(initial_dropped_label=0)

equilibria = myGame.lemke_howson_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0., 0., 0.]), array([0., 0., 1., 0.]))
(array([0., 1., 0., 0.]), array([0., 0., 0., 1.]))
(array([0., 1., 0., 0.]), array([0., 0., 0., 1.]))
(array([0., 1., 0., 0.]), array([0., 0., 0., 1.]))
(array([0., 1., 0., 0.]), array([0., 0., 0., 1.]))
(array([0., 1., 0., 0.]), array([0., 0., 0., 1.]))
(array([1., 0., 0., 0.]), array([0., 0., 1., 0.]))
(array([0., 1., 0., 0.]), array([0., 0., 0., 1.]))


The algorithm appears to have found $2$ distinct equilibria.